import type { Metadata } from "next";
import AmbientParallax from "@/components/AmbientParallax";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="relative overflow-x-hidden">
    <AmbientParallax />
  {/* GLOBAL AMBIENT BACKGROUND */}
  <div className="ambient-bg pointer-events-none">
  <div className="glow-wrapper">
    <div className="glow glow-main" />
  </div>
  <div className="glow-wrapper">
    <div className="glow glow-secondary" />
  </div>
  <div className="glow-wrapper">
    <div className="glow glow-tertiary" />
  </div>
</div>


  {/* SITE CONTENT */}
  <div className="relative z-10">
    {children}
  </div>

</body>


    </html>
  );
}
